### ISSUE TITLE
Message log extension does not show special characters in payload (docker container)

### ISSUE THREAD

**Issue by globz-eu** [hivemq/hivemq-community-edition#272] opened 2021-05-05 08:25 UTC
## Expected behavior
I'm using the [hivemq-mqtt-message-log-extension](https://www.hivemq.com/extension/mqtt-message-log-extension/)
When the payload 'HELLOĚŠČÍÚ' gets published on the topic 'test' the log output should be:
```
2021-05-05 08:06:14,394 INFO  - Received PUBLISH from client 'hmq_4gY4M_0_b99f31448f880747e4783cb1141628f2' for topic 'test': Payload: 'HELLOĚŠČÍÚ' QoS: '0', Retained: 'false'
```

## Actual behavior
Log output:
```
2021-05-05 08:06:14,394 INFO  - Received PUBLISH from client 'hmq_4gY4M_0_b99f31448f880747e4783cb1141628f2' for topic 'test': Payload: 'HELLO?????' QoS: '0', Retained: 'false'
```

### Steps
* Run the hivemq-ce container with the hivemq-mqtt-message-log-extension
* Publish a payload with special characters

### Reproducer code
```bash
docker run -v /path/to/hivemq-mqtt-message-log-extension:/opt/hivemq/extensions/hivemq-mqtt-message-log-extension -p 1883:1883 hivemq/hivemq-ce:2021.1
```
```bash
mosquitto_pub -t test -m 'HELLOĚŠČÍÚ'
```
Setting `LANG=C.UTF-8` in the container fixes the issue.

## Details
- Affected HiveMQ CE version(s): 2020.6, 2021.1
- Used JVM version:

**Comment by DC2-DanielKrueger** [comment] 2021-05-28 12:44
Hallo @globz-eu,

Indeed the reason for this behavior is the local language setting inside the container.  Per default it is: en_US.UTF-8 what will lead to the output with the '?' instead of the "correct" characters.
Nice catch with the LANG=C.UTF-8 fix, pointed directly in the right direction. As this is not a bug in the code, but needs to be adjusted in the container i close this issue and bring it in the dev team. 

Thank you very much for pointing this out. 

Best regards, 
Daniel

**Closed by DC2-DanielKrueger** 2021-05-28 12:44 UTC
