### ISSUE TITLE
Problem starting server: JMX agent throws MalformedException with Service URL contains non-ASCII character

### ISSUE THREAD

**Issue by bluexp1** [hivemq/hivemq-community-edition#210] opened 2020-09-09 18:12 UTC
I am trying to run hivemq on windows. after running run.bat I received this error:
```Error: Exception thrown by the agent : java.net.MalformedURLException: Service URL contains non-ASCII character 0x6f9
jdk.internal.agent.AgentConfigurationError: java.net.MalformedURLException: Service URL contains non-ASCII character 0x6f9
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:491)
        at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:447)
        at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)
Caused by: java.net.MalformedURLException: Service URL contains non-ASCII character 0x6f9
        at java.management/javax.management.remote.JMXServiceURL.<init>(JMXServiceURL.java:157)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:846)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:479)
        ... 2 more
```

Can somebody describe what the reason for this is?

**Comment by MicWalter** [comment] 2020-09-10 12:52
Hi @bluexp1,

If you could provide some additional information, currently I can not reproduce this with my Windows setup:
* Win 10 Pro (64bit)
* Java 11
* HiveMQ CE 2020.4 
* running run.bat as normal user (and then once with admin rights)

Also it would be nice to know if you ran the HiveMQ version out of the box, or if you made changes (like changing config.xml etc.).

Greetings,
Michael

**Comment by bluexp1** [comment] 2020-09-10 14:50
I am running on windows 10 Enterprise with java12 and HiveMQ CE 2020.2,
 where can I get HiveMQ CE 2020.4?
I didn't modify anything. I ran the program with its default configuration.

**Comment by MicWalter** [comment] 2020-09-10 19:59
Hi @bluexp1,
I could also not reproduce it with the provided setup, checking the exception again it seems the JMX agent is the root cause.
If possible you could disable JMX from the run.bat file and try again? For that add `rem` before `set "JAVA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010.....`

In below snippet JMX is disabled via the run.bat:
```
rem JMX Monitoring
rem set "JAVA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 
```

My current thought is that something like this is the problem: 
https://stackoverflow.com/questions/57836866/can-not-find-out-why-jmxremoteurl-contains-non-ascii-character
As `0x6f9` from the exception points towards the same issue described there:
http://software.hixie.ch/utilities/cgi/unicode-decoder/utf8-decoder?encoding=numeric&bytes=0xe0%200x9b%200xb9

Greetings,
Michael

**Comment by bluexp1** [comment] 2020-09-11 06:46
Trying HiveMQ CE 2020.4, I still get the same errors.

**Comment by bluexp1** [comment] 2020-09-11 07:05
@MicWalter , Thanks to the link you provided I solve the problem by changing windows regional format to english.
It seems that it's bug in java framework or something, though I am still wondering why disabling JMX doesn't have any effect!

**Comment by MicWalter** [comment] 2020-09-11 07:56
Good to hear that the problem is solved!

Could you please provide me the regional format you had when the error occurred? So I can reproduce this exception for further investigation.

And yes my comment about disabling JMX by commenting out the line was wrong, instead you only revert to the default settings of the JVM and since Java 6 the JMX is locally enabled by default (see [here](https://docs.oracle.com/javadb/10.10.1.2/adminguide/radminjmxenabledisable.html)). 

Greetings,
Michael

**Comment by bluexp1** [comment] 2020-09-11 08:12
The regional format was set to Persian.

**Comment by MicWalter** [comment] 2020-09-21 08:07
There seems to be no fix that is worth the time, as there is already a workaround.

I'll close this issue.

**Closed by MicWalter** 2020-09-21 08:07 UTC
Labels: question
