### ISSUE TITLE
No empty space on disk because of HiveMQ CE logs?

### ISSUE THREAD

**Issue by jayjupdhig** [hivemq/hivemq-community-edition#269] opened 2021-04-26 11:42 UTC
´Is it a feature or is it a bug?´
-> https://community.hivemq.com/t/many-gb-of-logs-after-a-few-months/519

Thanks in advance for your feedbacks...

**Comment by MicWalter** [comment] 2021-04-26 11:56
Possibly a duplicate from #213

**Comment by MicWalter** [comment] 2021-04-26 12:18
Closing this as used version was 2020.4 and #213 (which I'm sure is the root cause) was released with 2020.6

**Closed by MicWalter** 2021-04-26 12:18 UTC
Labels: duplicate
